timezone: Etc/UTC

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

paths:
  static: static
  uploads: static/images

commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'

collections_config:
  pages:
    path: content
    url: "/[slug]/"
    glob: 
      - "*.md"
      - "portfolios/_index.md"
      - "posts/_index.md"
    icon: text_ad
    _enabled_editors:
      - visual
    schemas:
      page:
        path: .cloudcannon/schemas/page.md
  portfolios:
    path: content/portfolios
    url: "/portfolios/[slug]/"
    glob: 
      - "!_index.md"
    schemas:
      default:
        path: .cloudcannon/schemas/portfolio.md
    icon: work
    _enabled_editors:
      - visual
    _inputs:
      category:
        type: text
        comment: Define which category this portfolio item should belong to in the portfolios list.
      portfolio_details:
        type: object
        options:
          preview:
            icon: work
            image:
              - key: image
            text:
              - key: heading
      portfolio_details.image:
        type: image
        options:
          paths:
            uploads: images/portfolio
  posts:
    path: content/posts
    url: "/posts/[slug]/"
    glob: 
      - "!_index.md"
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
    icon: newspaper
    _enabled_editors:
      - content
      - visual
    _inputs:
      categories:
        type: array
        comment: Define which categories this post should belong to on the blog page.
      categories[*]:
        type: text
      images:
        type: array
        options:
          structures: _structures.post_image
      link:
        type: text
        comment: The text used for this post's link in the list of posts.
      description:
        type: textarea
        comment: Used as the description for the post's preview in the list of posts.
    _structures:
      post_image:
        values:
          - value:
              image:
              image_alt:
            _inputs:
              image:
                type: image
                options:
                  paths:
                    uploads: images/blog
            preview:
              icon: image
              image:
                - key: image
              text:
                - key: image_alt
              subtext: 
                - key: image
  data:
    path: data
    disable_url: true
    _inputs:
      google_maps_api_key:
        comment: Add your key if you want to use google maps features within the site

_inputs:
  content_blocks:
    type: array
    options:
      structures: _structures.content_blocks
  hero_blocks:
    type: array
    options:
      structures: _structures.hero_blocks
      max_items: 1
      max_items_message: Only define one hero block, so that you don't have more than one <h1> element on a page.
  text_content:
    type: markdown
  seo_options:
    type: object
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  type:
    hidden: true


_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    image_size_attributes: true
