baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'fiction-hugo-template'

[pagination]
pagerSize = 3

[build]
writeStats = false

[taxonomies]
categories = "categories"
category = "category"

[markup.goldmark.renderer]
unsafe = true

[module]
replacements = "local/component-library -> ../component-library"
  [module.hugoVersion]
    extended = true
    min = '0.128.0'


[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'