# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Portfolio Details"
  description:
  icon: work
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  category: category-1
  image: /images/portfolio/portfolio-img1.jpg
  image_alt: Portfolio
  date: 
  title: 
  client: 
  services:
  project_url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
